version: '3'
services:
  mydb:
    image: ${POSTGRES_IMAGE}
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'game'
      POSTGRES_PASSWORD: 'game'

networks:
  default:
    external:
      name: ${TEST_DOCKER_NET}

volumes:
  db-data:
