module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  testTimeout: 80000,
  globals: {
    'ts-jest': {
      isolatedModules: false,
    },
  },
  // globalSetup: '<rootDir>/tests/setup.ts',
  moduleNameMapper: {
    '^@src/(.*)': '<rootDir>/src/$1',
  },
  transformIgnorePatterns: [`/node_modules/(?!${['typeorm']})`],

  collectCoverageFrom: [
    'src/**/*.{js,jsx,ts,tsx}',
    '!src/repositories/nexthand.ts',
    '!src/repositories/chipstrack.ts',
    '!src/repositories/admin.ts',
    '!src/api/promotion/index.ts',
    '!src/repositories/dev.ts',
    '!src/resolvers/dev.ts',
    '!src/resolvers/hello.ts',
    '!src/repositories/hello.ts',
    '!src/admin/index.ts',
    '!src/botrunner/index.ts',
    '!src/3rdparty/agora.ts',
    '!src/firebase/index.ts',
    '!src/gameserver/index.ts',
    '!src/janus/index.ts',
    '!src/repositories/appcoin.ts',
    '!src/repositories/gamesettings.ts',
    '!src/repositories/gameupdates.ts',
    '!src/repositories/promotion.ts',
    '!src/repositories/timer.ts',
    '!src/repositories/reward.ts',
    '!src/repositories/promotion_consumed.ts',
    '!src/digitalocean/index.ts',
    '!src/resolvers/appcoin.ts',
    '!src/utils/log.ts',
    '!src/scheduler/index.ts',
    '!src/timer/index.ts',
    '!src/timer/nats.ts',

    // '!<rootDir>/node_modules/"',
  ],
  collectCoverage: true,
  coverageDirectory: 'cov-int',
  coverageReporters: ["json", "html"],

  // testPathIgnorePatterns: ['/node_modules', '/unit-tests'],
};
