module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  testTimeout: 80000,

  moduleNameMapper: {
    '^@src/(.*)': '<rootDir>/src/$1',
  },
  // globalSetup: '<rootDir>/tests/testSetup.ts',
  // collectCoverageFrom: [
  //   'src/**/*.{js,jsx,ts,tsx}',
  //   '!<rootDir>/node_modules/"',
  //   ],
  collectCoverage: true,
  coverageReporters: ["json", "html"],
  coverageDirectory: 'cov-unit',
  collectCoverageFrom: [
    'src/**/*.{js,jsx,ts,tsx}',
    '!src/repositories/nexthand.ts',
    '!src/repositories/chipstrack.ts',
    '!src/repositories/admin.ts',
    '!src/api/promotion/index.ts',
    '!src/repositories/dev.ts',
    '!src/resolvers/dev.ts',
    '!src/resolvers/hello.ts',
    '!src/repositories/hello.ts',
    '!src/admin/index.ts',
    '!src/botrunner/index.ts',
    '!src/3rdparty/agora.ts',
    '!src/firebase/index.ts',
    '!src/gameserver/index.ts',
    '!src/janus/index.ts',
    '!src/repositories/appcoin.ts',
    '!src/repositories/gamesettings.ts',
    '!src/repositories/gameupdates.ts',
    '!src/repositories/promotion.ts',
    '!src/repositories/timer.ts',
    '!src/repositories/reward.ts',
    '!src/repositories/promotion_consumed.ts',
    '!src/digitalocean/index.ts',
    '!src/resolvers/appcoin.ts',
    '!src/utils/log.ts',
    '!src/scheduler/index.ts',
    '!src/timer/index.ts',
    '!src/timer/nats.ts',
    '!src/internal/admin.ts',
    '!src/internal/bot.ts',
    '!src/internal/game.ts',
    '!src/internal/gameserver.ts',
    '!src/internal/hand.ts',
    '!src/internal/metrics.ts',
    '!src/nats/index.ts',
    '!src/internal/user.ts',


    // temporarily disable directories
    '!src/email/*.ts',
    '!src/entity/game/*.ts',
    '!src/entity/history/*.ts',
    '!src/entity/player/*.ts',
    '!src/entity/debug/*.ts',
    '!src/entity/*.ts',
    
    // '!<rootDir>/node_modules/"',
  ],  
  testPathIgnorePatterns: ['/node_modules', '/tests'],
};
