module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  testTimeout: 80000,
  // globalSetup: '<rootDir>/tests/setup.js',
  moduleNameMapper: {
    '^@src/(.*)': '<rootDir>/src/$1',
  },
  collectCoverageFrom: [
    'src/**/*.{js,jsx,ts,tsx}',
    '!src/repositories/nexthand.ts',
    '!src/repositories/chipstrack.ts',
    '!src/repositories/admin.ts',
    '!src/api/promotion/index.ts',
    '!src/repositories/dev.ts',
    '!src/resolvers/dev.ts',
    '!src/resolvers/hello.ts',
    '!src/repositories/hello.ts',
    '!src/admin/index.ts',
    '!src/botrunner/index.ts',
    // '!<rootDir>/node_modules/"',
  ],
  // collectCoverage: true,
  // coverageDirectory: 'cov',
  // testPathIgnorePatterns: ['/node_modules', '/unit-tests'],
};
