version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build-and-test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Lint
          command: make lint
      - run: 
          name: Compile TS
          command: make build
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Start redis
          command: docker run -d --name redis  -p 6379:6379 redis:6.0.9
          background: true
      - run:
          name: Run unit tests
          command: make unit-tests
      - run:
          name: Run tests
          command: make tests
      - run:
          name: Run script tests
          command: make script-tests  
      - run:
          name: Stop redis
          command: docker rm -f redis      
workflows:
    build-and-test:
      jobs:
        - build-and-test
