version: 2.1
orbs:
  node: circleci/node@4.3.0
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: '16.1.0'
    steps:
      - checkout
      - run:
          name: Lint
          command: make lint
      - run: 
          name: Compile TS
          command: make build
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build test images
          command: make docker-build-test
      - run:
          name: Run unit tests
          command: make docker-unit-tests
      - run:
          name: Run script tests
          command: make docker-script-tests
      - run:
          name: Run tests
          command: make docker-tests
      - when:
          condition:
            equal: [ master, <<pipeline.git.branch>> ]
          steps:
            - run:
                name: Build Docker images (master only)
                command: make docker-build
            - run:
                name: Publish Docker images (master only)
                command: make publish

workflows:
    build-and-test:
      jobs:
        - build-and-test
