version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: make install_deps
            - run: make build
            - run: make test
workflows:
    build-and-test:
      jobs:
        - build-and-test