#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE livegames;
    CREATE DATABASE history;
    CREATE DATABASE users;
    GRANT ALL PRIVILEGES ON DATABASE livegames TO "$POSTGRES_USER";
    GRANT ALL PRIVILEGES ON DATABASE history TO "$POSTGRES_USER";
    GRANT ALL PRIVILEGES ON DATABASE users TO "$POSTGRES_USER";    
EOSQL
