FROM node:14.7.0-alpine3.12
RUN apk --no-cache add python3 build-base
RUN apk --no-cache add --update yarn curl
RUN ln -s /usr/bin/python3 /bin/python
WORKDIR /app
COPY yarn.lock .yarnclean package.json package-lock.json ./
RUN yarn install 
COPY . .
ENV NODE_OPTIONS=--max-old-space-size=2048
RUN yarn compile 
