name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        node_version:
          - 14
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: printenv && pwd && ls -l
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          cache: npm
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ./node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node_version }}-${{ hashFiles('package-lock.json') }}
      - name: Build
        run: make build
      - name: Lint
        run: make lint
      - name: Build Test Image
        run: make docker-build-test
      - name: Unit Test
        run: make docker-unit-tests
      - name: API Test
        run: make docker-tests

  # publish:
  #   needs: build
  #   if: success() && github.ref == 'refs/heads/master'
